#Mkboot
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --dtb $(TARGET_PREBUILT_DTB)
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION)
BOARD_KERNEL_IMAGE_NAME := Image
BOARD_FLASH_BLOCK_SIZE := 131072 # (BOARD_KERNEL_PAGESIZE * 64)

#prebuilt
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb.img
TARGET_FORCE_PREBUILT_KERNEL := true
ifeq ($(TARGET_FORCE_PREBUILT_KERNEL),true)
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb.img
BOARD_INCLUDE_DTB_IN_BOOTIMG := 
endif

# this what you need to define you can use any tool to read and extract boot to know 
#BOARD_BOOTIMG_HEADER_VERSION := 2
#BOARD_KERNEL_BASE := 0x40078000
#BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2 
#BOARD_KERNEL_PAGESIZE := 2048
#BOARD_RAMDISK_OFFSET := 0x07c08000
#BOARD_KERNEL_TAGS_OFFSET := 0x0bc08000
#also you will need to put the kernel and dtb.img from boot dump to prebuilt folder
